### PR TITLE
Ossia pd

### PR DESCRIPTION
**Pull request by avilleret**
it is still in an early state with lots of debugging print and lots of bugs
ossia.parameter, ossia.model and ossia.device seem to work fine
but issue with ossia.remote when (un-)registering

### CODE REVIEW

**Comment by avilleret** [comment]
TODO : add help files ...

**Comment by bltzr** [comment]
Hi ! 

Sounds promising !

Do you need any reviewing from some of us before merging the pull resquest ?

**Comment by jcelerier** [comment]
Seems to work !

**Comment by jcelerier** [comment]
woohoo
GG !

**Pull request merged**
